PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE books(id integer NOT NULL, title TEXT NOT NULL, author text NOT NULL, isbn text NOT NULL, uri text, summary text not null);
INSERT INTO books VALUES(1,'Opening the Hand of Thought','Kosho Uchiyama','9780861713578','https://wisdomexperience.org/product/opening-hand-thought/','For over thirty years, Opening the Hand of Thought has offered an introduction to Zen Buddhism and meditation unmatched in clarity and power. This is the revised edition of Kosho Uchiyama’s singularly incisive classic.');
INSERT INTO books VALUES(2,'You Are The One You''ve Been Waiting For','Richard C Schwartz','9780615249322','https://ifs-institute.com/store/37','In this book, Richard Schwartz, the developer of the Internal Family Systems Model, applies the IFS Model to the topic of intimate relationships in an engaging, understandable, and personal style. Therapists and lay people alike will find this book to be an insightful exploration of how cultivating a relationship with the Self—the wise center of clarity, calmness, and compassion in each of us—creates the foundation for courageous love and resilient intimacy: the capacity to sustain and nourish a healthy intimate relationship. Self-leadership also allows us to embrace our partner''s feedback and use it to discover aspects of ourselves that seek healing. The book includes user-friendly exercises to facilitate learning.');
CREATE TABLE replied_entries (id integer NOT NULL, reddit_id TEXT NOT NULL);
INSERT INTO replied_entries VALUES(0,'dummy');
INSERT INTO replied_entries VALUES(1,'udcix1');
INSERT INTO replied_entries VALUES(2,'udcf4p');
INSERT INTO replied_entries VALUES(3,'i4gljhh');
INSERT INTO replied_entries VALUES(4,'i4glk3q');
INSERT INTO replied_entries VALUES(5,'i4gletn');
INSERT INTO replied_entries VALUES(6,'u25q2s');
INSERT INTO replied_entries VALUES(7,'u25pch');
INSERT INTO replied_entries VALUES(8,'uem6bf');
INSERT INTO replied_entries VALUES(9,'i6ny33o');
CREATE TABLE opted_in_users (id integer NOT NULL, reddit_username TEXT NOT NULL);
INSERT INTO opted_in_users VALUES(0,'dummy');
INSERT INTO opted_in_users VALUES(1,'HoweverItHasToHappen');
COMMIT;
