[tool.pytest.ini_options]
testpaths = ['tests']
python_functions = ['test_*', 'it_*']
pythonpath = [
    ".","src","rsarb","util", "src/rsarb"
]

[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"